# pytorch初步学习
基于[pytorch的官方文档](https://pytorch-cn.readthedocs.io/zh/latest/)

In [10]:
import torch
import numpy as np

## 一：张量（Tensor）
    Tensor是torch的基础数据结构

#### 1.1 Tensor的创建

In [19]:
#Tensor可以由数据直接赋值
data=[[1,2],[3,4]]
x=torch.tensor(data)
print(x)
print(type(x))
print(x.shape)

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
torch.Size([2, 2])


In [14]:
#Tensor可以用np.array转化得到
np_arr=np.array(data)
print(np_arr)
x=torch.from_numpy(np_arr)

[[1 2]
 [3 4]]


In [18]:
#随机或全1，全0
shape=(2,3,)
rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.8629, 0.5663, 0.3713],
        [0.7071, 0.3847, 0.2497]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### 1.2 Tensor的运算

In [46]:
#torch.cat可以用于多个tensor的连接
x=torch.randn(2,3)
print(f"x={x}")
x1=torch.cat((x,x,x),0)
x2=torch.cat((x,x,x),1)
print(f"1:{x1}")
print(f"2:{x2}")


x=tensor([[-1.7579, -0.4969, -0.0050],
        [-1.2971,  0.3436,  2.0473]])
1:tensor([[-1.7579, -0.4969, -0.0050],
        [-1.2971,  0.3436,  2.0473],
        [-1.7579, -0.4969, -0.0050],
        [-1.2971,  0.3436,  2.0473],
        [-1.7579, -0.4969, -0.0050],
        [-1.2971,  0.3436,  2.0473]])
2:tensor([[-1.7579, -0.4969, -0.0050, -1.7579, -0.4969, -0.0050, -1.7579, -0.4969,
         -0.0050],
        [-1.2971,  0.3436,  2.0473, -1.2971,  0.3436,  2.0473, -1.2971,  0.3436,
          2.0473]])


In [49]:
#torch.chunk用于将tensor分块
#torch.gather用于聚合张量的index(奇怪的操作，不知道哪里用得上)
x=torch.randn(2,2)
print(x)
torch.gather(x,1,torch.LongTensor([[0,0],[1,0]]))
#torch.index_select用于沿轴切片并组合
#torch.masked_select用于加mask
#类似的函数过多，之后遇到再研究

tensor([[ 0.3373, -0.2817],
        [-1.2712,  0.8891]])


tensor([[ 0.3373,  0.3373],
        [ 0.8891, -1.2712]])